### PR TITLE
Pass Version Number on every request

### LINKED ISSUE #67: Julian Wants Verison numbering on every request
This will need an http interceptor

http://www.webdeveasy.com/interceptors-in-angularjs-and-useful-examples/

### PR DESCRIPTION
**Pull request by torch2424**
closes #67 

This intercepts every request to the backend and adds "Version" to the params or data (depending on get or post method), to the backend

### CODE REVIEW

**Comment by torch2424** [comment]
I tested this on web and device, but another run through would be nice

**Comment by julianpoy** [comment]
Just let me know when this is ready to be tested and pulled and assign me :)

**Comment by torch2424** [comment]
Ooops this was ready accideentally assigned myself

**Comment by julianpoy** [comment]
I just noticed this doesn't handle the responses like #67 specifies.

**Pull request merged**
