### PR TITLE
No Autofill

### LINKED ISSUE #36: Autocomplete breaks reg-form
When autocompleting, the registration form is broken and keeps the reg button disabled.

### PR DESCRIPTION
**Pull request by torch2424**
closes #36 

I suggest testing this however, as I could only get this bug on the login page, and not the register page

### CODE REVIEW

**Comment by julianpoy** [comment]
All fields seem to be great now, except for the credit card field. For some reason that autofills now.

**Comment by torch2424** [comment]
Fixed CC fields hopefully, I am not getting the autofill bug, so I will need you to test it

**Comment by julianpoy** [comment]
screenshot from 2016-02-04 15-50-26

Not fixed on CC field. All other fields test fine.

**Comment by torch2424** [comment]
I have class in a half hour, and a broken dev environment. I think you may have to finish up the issue. As I cannot seem to dulicate it in my chrome as well. possibly try clearing your cookies and trying to see if chrome catches on again?

**Pull request merged**
