### PR TITLE
Page Editing

### PR DESCRIPTION
**Pull request by torch2424**
Pages can now be edited. The edit page button shall be removed with #27 but everything has beent tested and working great! :)

### CODE REVIEW

**Comment by julianpoy** [comment]
Excellent work!

**Comment by julianpoy** [comment]
Excellent work!

**Comment by julianpoy** [comment]
Is the editPage branch still useful? If not, please delete thanks :+1:

**Comment by torch2424** [comment]
No, it is not, I shall delete

**Pull request merged**
